import Head from 'next/head';
import Hero from '../components/hero';
import AppWrap from '../components/app-wrap';

const Home = () => {

  return (
    <div className="app">
      <Head>
        <title>Welcome To NixLab Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="NixLab,nixlab,webdevelopment,androidappdevelopment,iOSappdevelopment" />
        <meta name="google-site-verification" content="j7ODdQNwjVQNYmNEX_5boI9PagNu3Uoiu2EL-yVpBI0" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='apple-touch-icon' href='/logo_small.png' />
      </Head>

      <Hero />

    </div>
  );

}

export default AppWrap(Home, 'home');
